# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    steps:
      - checkout

      # Install any necessary dependencies
      - run: <dependency_installation_command>

      # Build and test the program
      - run: <build_command>
      - run: <test_command>

      # Optionally, include error reporting tools
      - run: <error_reporting_command>

      # Deploy the program to a container
      - run: <deployment_command>
